version: '3.8'

services:

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./MySQL_data:/var/lib/mysql
    ports:
      - '${POSTGRES_PORT:-3306}:3306'
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 3s
      timeout: 3s
      retries: 3